nelmio_api_doc:
    areas:
        path_patterns:
            - ^/api(?!/doc$)
    documentation:
        info:
            title: Simply Delivery API
            description: 
            version: 1.0.0
        